#!/usr/bin/env bash
# script that displays info about domains
# +and subdomains

# Function to get the DNS record
get_dns() {
	local domain=$1
	local subdomain=$2

	local record_type
	record_type=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | awk '{print $4 }')
	local destination
	destination=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | awk '{print $5 }')
	
	echo "The subdomain $subdomain is a $record_type record and points to $destination" # +ignore SC2086
}

if [ -z "$1" ]
then
	echo "Error domain is mandatory"
	exit 1
fi
if [ -z "$2" ]
then
	for subdomain in www lb-01 web-01 web-02; do
		get_dns "$1" "$subdomain"
	done
else
	get_dns "$1" "$2"
fi
