#!/usr/bin/env bash
# script that displays info about domains
# +and subdomains

# Function to get the DNS record
get_dns() {
	local domain=$1
	local subdomain=$2

	local record
	record=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 |tr '\n' ' ')
	echo "$2 $record" | awk '{print "The subdomain " $1 " is a "$2 " record and points to " $3}'
}

if [ -z "$1" ]
then
	echo "Error domain is mandatory"
	exit 1
fi
if [ -z "$2" ]
then
	for subdomain in www lb-01 web-01 web-02; do
		get_dns "$1" "$subdomain"
	done
else
	get_dns "$1" "$2"
fi
