#!/usr/bin/env bash
# A script that installs and configures nginx


sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'

if [ ! -d "/etc/nginx/html" ]; then
  mkdir /etc/nginx/html
fi

sudo touch /etc/nginx/html/index.html
sudo touch /etc/nginx/html/404.html

sudo bash -c 'echo "Hello World!" > /etc/nginx/html/index.html'
sudo bash -c "cat << 'EOF' > /etc/nginx/html/404.html
Ceci n'est pas une page
EOF"

sudo bash -c "cat << 'EOF' > /etc/nginx/sites-available/default
server {
  listen  80;
  listen  [::]:80 default_server;
  root  /etc/nginx/html;
  index index.html index.htm;

  location  /redirect_me {
    return 301 https://anabanti-akachi.github.io/;
  }

    error_page  404 /404.html;

    location  /404 {
    root  /etc/nginx/html;
    internal;
  }
}
EOF"

sudo service nginx restart
