#!/usr/bin/env bash
# A script to install HAproxy on a server

sudo apt-get install \
	--no-install-recommends software-properties-common
echo | sudo add-apt-repository ppa:vbernat/haproxy-2.0

sudo apt-get update

sudo apt-get install -y haproxy=2.0.\*

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null
sudo cp /etc/haproxy/haproxy.cfg{,.original}
# sudo touch /etc/haproxy/haproxy.cfg

printf "%s" "
frontend www
	mode http
	bind :80
	default_backend hbnb

backend hbnb
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 355598-web-01 54.172.4.252:80 check
	server 355598-web-02 54.175.109.84:80 check

" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
