#!/usr/bin/env bash
# A script to install HAproxy on a server

sudo apt-get update
sudo apt-get upgrade -y

sudo apt-get install \
	--no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0

sudo apt-get update

sudo apt-get install haproxy=2.0\* -y
sudo bash -c "cat << 'EOF' >> /etc/haproxy/haproxy.cfg
	no option http-use-htx

frontend website
	bind :80
	default_backend web_servers

backend web_servers
	balance roundrobin
	server 355598-web-01 54.172.4.252:80 check
	server 355598-web-02 54.175.109.84:80 check
EOF"

sudo service haproxy start
