#!/usr/bin/env bash
# This program handles signals from another program

sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'
handle_sigint() {
	echo "Y U no love me?!"
}
handle_sigterm() {
	echo "I hate the kill command"
	sudo bash -c 'rm /var/run/myscript.pid'
	exit
}
handle_sigquit() {
	sudo bash -c 'rm /var/run/myscript.pid'
	exit
}
trap 'handle_sigint' SIGINT
trap 'handle_sigterm' SIGTERM
trap 'handle_sigquit' SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
