#!/usr/bin/env bash
# This script manages a process like a daemon
#+ start stop and restart
if [ $# -lt 1 ]
then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
fi
for arg in "$@"
do
	if [[ "$arg" != "start"  && "$arg" != "stop" && $arg != "restart" ]]
	then
		echo "Usage: manage_my_process {start|stop|restart}"
	else
		if [[ "$arg" == "start" ]]
		then
			./manage_my_process &
			echo $! | sudo tee /var/run/my_process.pid > /dev/null
			echo "manage_my_process started"
		fi
		if [[ "$arg" == "stop" ]]
		then
			if [ -f /var/run/my_process.pid ]
			then
				kill -SIGTERM "$(cat /var/run/my_process.pid)"
				sudo rm /var/run/my_process.pid
				echo "manage_my_process stopped"
			else
				echo "manage_my_process is not running"
			fi
		fi
		if [[ "$arg" == "restart" ]]
		then
			if [ -f /var/run/my_process.pid ]
			then
				kill -SIGTERM "$(cat /var/run/my_process.pid)"
				sudo rm /var/run/my_process.pid
				./manage_my_process &
				echo $! | sudo tee /var/run/my_process.pid > /dev/null
				echo "manage_my_process restarted"
			else
				echo "manage_my_process is not running"
			fi
		fi
	fi
done
