#!/usr/bin/env bash
# This code display 8 and 4 in meaning in chinese culture while looping from 1 to 10
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
