#!/usr/bin/env bash
# creates a database replication config

sudo cp /etc/mysql/mysql.conf.d/mysqld.cnf{,.original}
sudo printf "%s\n" "
# Copyright (c) 2014, 2023, Oracle and/or its affiliates.
[mysqld]
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
datadir         = /var/lib/mysql
log-error       = /var/log/mysql/error.log
# By default we only accept connections from localhost
# bind-address  = 127.0.0.1
# Disabling symbolic-links is recommended to prevent assorted security risks
symbolic-links=0
server-id       = 1
log_bin         = /var/log/mysql/mysql-bin.log
binlog_do_db    = tyrell_corp
" > /etc/mysql/mysql.conf.d/mysqld.cnf

sudo service mysql restart
