#!/usr/bin/env bash
#  change default nginx user 
# +and listen on 8080

# note apache listens on 8080 already

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf

pkill apache2

sudo -u nginx service nginx start
